

== Advanced Features

=== Wiretap

The transport subsystem of Muon injects a WiretapChannel into every connection that is made. This allows you to optionally
read the messages moving in and out of the transport and further interpret them. The messages themselves are immutable,
and so you recieve the message itself for processing.

Ordinarily, this is used to record the way a service communicates with the rest of the distributed application. This
is particularly useful when designing and building a new communication protocol.

Image a service with a single RPC endpoint that accepts an undefined object data structure, which represent using a Map.
 It then responds inline wth the number 42. A very simple service.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=setupRPC]
----

We would like to generate a list of all the services that are calling this one, without altering the business method.

We could implement this using a wiretap, this will extract a stream of all the requests that match a particular filter.
The stream interface provided implements the Reactive Stream interface.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=wiretap]
----
<1> The services that have connected to this one via the RPC endpont.
<2> A Reactive Streams `Subscriber`, converting the messages into the list of origin service names
<3> Adding the tap into the Muon transport subsystem
<4> The filter matches for the `step` field on the `MuonMessage`, picking out particular message types for processing.

Whenever you then perform an RPC communication, the Request ```TransportMessage``` events will be selected by your wiretap
 and passed into the Subscriber, in this case the Rx Subscriber.

=== Encoding Support

To go across a network, all payloads used in Muon protocols ultimately need to be converted to arrays of bytes.

Muon can uses a variety of encoding methods, depending on your configuration and the types that you want to use.

The default codec in Muon Java for internal types is now *Avro*, and it is recommended that you use Avro if you can, as this gives an improved experience for integration with external tooling, as Muon can negotiate the sending of Avro schemas and provides them to clients via the Introspection protocol.

There are different sources of Avro Schema information that Muon can use :-

* You generate a SpecificRecord extending class from an existing Schema, using the Avro tools.
//* You load in a Converter type,
* For regular POJOS with no more information, Muon will auto create a schema from your Java type and send that. This does not include any validation rules, and auto generates the Schema types from the Java types, which may be incorrect. All fields are marked as Nullable

The fallback Codec is JSON, encoded using GSON. This is used when no other codec can be negotiated, such as for Muon Node/ MuonJS

For Muon implementations that don't support Avro, Muon will send JSON encoded messages and process the responses from JSON into Java types.
