
== Of APIs and Protocols

Muon, at heart, is a toolkit for building new _Reactive APIs_. These are message based and give the ability to build true APIs that confirm to the guiding principles of the Reactive Manifesto.

To get you started, Muon provides a set of prebuilt types of API that give you semantics beyond HTTP or other RPCish protocols

* Reactive Streams. Managed Streaming, with explicit client controlled back-pressure. Follows the Reactive Streams semantics and in Muon Java, fully supports the interfaces. - https://github.com/muoncore/stack-reactive-streams
* Extended RPC - http://github.com/muoncore/stack-rpc
* Persisted Event Logs - http://github.com/muoncore/stack-event

Once you have constructed a Muon instance, connected it to a Discovery and enabled some transport, you can begin to wrap it with Protocols. This give different types of behaviour, richer semantics.

In addition to the ones described here, you can write your own!

=== Example Protocols

Here we look at RPC and Reactive Streams. These are hosted at  http://github.com/muoncore/stack-rpc and http://github.com/muoncore/stack-reactive-streams

You will find the Java implementations alongside implementations for other Muon implementations of those API types.

==== RPC

Request/ Response is a well understood communication style where you make a single request and expect to receive a single response

Muon supports this style of communication, over it's naturally scalable reactive and event based channel communication.

===== Simple RPC

Here is the simplest possible Muon RPC endpoint. It accepts any data pushed to it, and responds with a simple text message

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPC.java[tags=server]
----

The client for this looks like

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPC.java[tags=client]
----

The Response object contains meta data about the response, eg, if it succeeded.


===== Making it Reactive

The handler does not need to response synchronously as in the above example. The response can be invoked from any context, and by any thread.

This will cause an event to flow back down the channel and complete the request/ response cycle.

An example of this in action is

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPCAsync.java[tags=main]
----
<1> As requests arrive, add them to a Queue for processing
<1> Start a thread to process the requests in serial
<1> Send a response. This is on a different thread
<1> Original thread drops out of this method and is re-used by Muon

This demonstrates adding the requests onto a queue and processing them asynchronously.

Be aware that the request will time out on both the client and server side, depending on your configuration.

==== Reactive Streams

Muon is built to enable the creation of streams easily. Internally everything is treated as a _channel_, a naturally streaming
construction.

This is best accessed via the Reactive Streams API, a cross industry effort to standardise streaming communication with back pressure.

To publish a new stream, create a _Publisher_ and pass it into the publishStream method, giving it a name, and the semantics of the stream.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveStreams.java[tags=server]
----
<1> Create the ReactiveStreamServer. The protocol is then attached to the running Muon instance and will be visible in the introspection report.
<1> Create a re-usable new RxJava Flowable (which implements `Publisher`) and expose it on a Muon endpoint.
<1> DYnamically generate a `Publisher`. Parameters can be passed to the endpoint by the client, which allows the endpoint to load data, transform the stream or other tasks before providing the Publisher to be connected to by the remote Subscriber
<1> Access the passed params
<1> Dynamically build a new `Publisher`

Here, we use _RxJava_ to demonstrate the creation of a Publisher, however any Reactive Streams compatible framework or library could be used.

To access the data from another service, use the subscribe method, passing in the logical Muon discovery url.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveStreams.java[tags=client]
----
<1> Subscribe to the given Rx endpoint. Pass in a Reactive Streams `Subscriber`
<2> Manage back pressure from the client. Here, we just request as much data as possible.
<3> Receive the data. `StreamData` lets you selectively decode it in various ways to allow heterogeneous data flow over the stream and be correctly decoded.
<4> Subscribe to a dynamic endpoint, passing a parameter in the query string.

Again, this example uses Java and shows two separate services communicating using a reactive message stream, with back pressure support managed by the Reactive Stream Subscriber.
