
== Core Features

=== Reactive RPC

Request/ Response is a well understood communication style where you make a single request and expect to receive a single resonse

Muon supports this style of communication, over it's naturally scalable reactive and event based channel communication.

==== Simple RPC

Here is the simplest possible Muon RPC endpoint. It accepts any data pushed to it, and responsds with a simple text message

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPC.java[]
----

The client for this looks like

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPC.java[]
----

The Response object contains meta data about the reponse, if it succeeded.


==== Making it Reactive

The handler does not need to response synchronously as in the above example. The response can be invoked from any context, and by any thread.

This will cause an event to flow back down the channel and complete the request/ response cycle.

An example of this in action is

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPCAsync.java[]
----
//TODO, callouts and description

This demonstrates adding the requests onto a queue and processing them asynchronously.

Be aware that the request will time out on both the client and server side, depending on your configuration.

==== Batch handling RPC

A common failure of RPC based systems is that they attempt to perform too much work in concurrently, and in logical isolation.
This then ends up causing thread thrashing, overwhelming of the thread pool or overload on some backing data store.

Taking the above mechanism to it's logical conclusion, it becomes trivial to batch up the processing of request.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPCBatch.java[]
----

This example will, every 5 seconds, drain the queue, generate a single answer and send it to all of them.

=== Reactive Streams

Muon is built to enable the creation of streams easily. Internally everything is treated as a _channel_, a naturally streaming
construction.

This is best accessed via the Reactive Streams API, a cross industry effort to standardise streaming communication with back pressure.

To publish a new stream, create a _Publisher_ and pass it into the publishStream method, giving it a name, and the semantics of the stream.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveStreams.java[]
----

Here, we use _Spring Reactor_ to demonstrate the creation of a Publisher, however any Reactive Streams compatible framework or library could
be used.

To access the data from another service, use the subscribe method, passing in the logical Muon discovery url.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveStreams.java[]
----

Again, this example uses Java and shows two separate services communicating using a reactive message stream, with back pressure support
managed by Reactor.


=== Wiretap

The transport subsystem of Muon injects a WiretapChannel into every connection that is made. This allows you to optionally
read the messages moving in and out of the transport and further interpret them. The messages themselves are immutable,
and so you recieve the message itself for processing.

Ordinarily, this is used to record the way a service communicates with the rest of the distributed application. This
is particularly useful when designing and building a new communication protocol.

Image a service with a single RPC endpoint that accepts an undefined object data structure, which represent using a Map.
 It then responds inline wth the number 42. A very simple service.

[source,java]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=setupRPC]
----

We would like to generate a list of all the services that are calling this one, without altering the business method.

We could implement this using a wiretap, this will extract a stream of all the requests that match a particular filter.
The stream interface provided implements the Reactive Stream interface.

[source,java]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=wiretap]
----
<1> The services that have connected to this one via the RPC endpont.
<2> A Spring Reactor Broadcaster, converting the messages into the list.
<3> Adding the tap into the Muon transport subsystem
<4> The filter matches for the EventType field on the TransportMessage, picking out particular messages.

Whenever you then perform an RPC communication, the Request ```TransportMessage``` events will be selected by your wiretap
 and passed into the Subscriber, in this case the Reactor Broadcaster.

[source,java]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=fireRPC]
----

As many wiretaps as you like can be active. You may add another Wiretap later on to select the Response messages, and it will then begin
to receive all the messages required.

[source,java]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=wiretap2]
----
