
== Extending Muon Java

In common with all Muon libraries, Muon Java is a restricted implementation of Communicating Sequential Processes.
Extension then mostly involves creating and exposing various combinations of processes and channels.

=== Encoding

=== Transports

=== Discovery


=== Adding a new interaction protocol

Before reading on, many systems won't need to do this. The baked in protocols (RPC, Streaming etc) are generally good enough
in most circumstances. If you do have a specific need to control the way your services interact in a more granular way then read on!

To implement a new protocol, you need to define the API(s) that you want to provide to your users, define the event interchange
that will need to happen to communicate that between services, and then create the processes need to bring those events to life.

This guide focuses on how to implement this in Muon-Java. For a fuller discussion on event protocols, see the main guide.

TODO, link to main guide on protocols

==== Designing a Protocol

==== Client Side

===== Designing Building a Muon Client Process

===== Designing the User API and Protocol Stack

==== Server Side

===== Designing Building a Muon Server Process

===== Registering the ServerStack
