
Muon Java is the implementation of the Muon microservices toolkit, for the Java platform. Muon enables you to easily build
microservices in many languages that have richer, more performant and fully reactive communication semantics and gain access
to Muon compatible services written in other languages without having to sacrifice the rich semantics or performance.

== A Microservice based system in 5 minutes

The quickest way to start a new Muon Java Microservice is to use _Spring Boot_ and the _Spring CLI_. You can see deeper information
later in this guide.

You can install this by following the instructions at spring.io or using _SDK Man_

[source,shell]
```
curl -s get.sdkman.io | bash source "$HOME/.sdkman/bin/sdkman-init.sh"

sdk install springboot
```

You can then create a new Spring Boot based application as a Groovy script.

[source,groovy,indent=0]
----
include::/src/main/groovy/io/muoncore/example/user/UserService.groovy[lines=17..32]
----
<1> Use Spring Boot annotations to start up a Muon instance.
<2> Declare that this class has Muon operations to discover
<3> Declare an RPC endpoint (see RPC).
<4> Send data back to the client, in this case including the current process identifier.

Here, we have configured a full muon service that makes available a single endpoint using the RPC _protocol_.  This protocol gives
an easy way to make a request and wait until a single response is received. Next, you can create another microservice
that exposes this to the outside world.

[source,groovy,indent=0]
----
include::src/main/groovy/io/muoncore/example/gateway/Gateway.groovy[lines=18..36]
----
<1> Gain access to the _muon_ instance that has been created.
<2> Configure Spring MVC to listen on an HTTP endpoint
<3> Use the muon instance to make an RPC call

Here, we have used Spring MVC, configured again via Spring Boot. This gives an easy way to start up an HTTP container
and make it accessible. When you call http://localhost:8080/ you will receive an http response. The body of that response
will be created from the data supplied by the UserService Microservice.

You have successfully built a distributed system, congratulations!

These will run in production, as independent services and require no underlying platform or runtime.

