

== A Microservice based system in 5 minutes

The quickest way to start a new Muon Java Microservice is to clone the example
repo at https://github.com/muoncore/muon-java-gradle-example

This is set up to use Gradle as the build tool and Java as the application
language.

First, install the Muon CLI, then clone this repository.

This project has an example service already in there that looks similar to

```java
public class MuonServerExample {


    public static void main(String[] args) throws Exception {
        AutoConfiguration config = MuonConfigBuilder
                      .withServiceIdentifier("example-service").build(); // <1>

        Muon muon = MuonBuilder.withConfig(config).build();              // <2>

        muon.handleRequest(all(), request -> {                           // <3>
            System.out.println("A request has been made ");
            Map data = new HashMap();
            data.put("Hello", "world " + System.currentTimeMillis());
            request.ok(data);                                            // <4>
        });
        System.out.println("Use Ctrl-C to exit");
    }
}
```
<1> Create a muon configuration using a fluent interface builder.
<1> Construct a Muon instance from the config. It will appear in the network soon after this.
<1> Setup an RPC Protocol Handler, for all request paths.
<1> When invoked, respond to the RPC request with some manufactured data.

You can run this from a prebuilt Gradle task

```bash
> ./gradlew runServer
```

You can then use the Muon CLI to interact with the new service, using the name `example-service` set above as it's identifier

```bash
> muon rpc rpc://example-service/
```

You will see the results from the example service that should look like

```bash
david@patmos:~/$ muon rpc rpc://example-service/hello

┌────────────┬──────────────────────────────┬───────────────────────────────────────────────┐
│ STATUS     │ CONTENT/TYPE                 │ BODY                                          │
├────────────┼──────────────────────────────┼───────────────────────────────────────────────┤
│ 200        │ application/json             │ {"Hello":"world 1481639846708"}               │
└────────────┴──────────────────────────────┴───────────────────────────────────────────────┘

========= RESPONSE FULL BODY: ========================================================

{ Hello: 'world 1481639846708' }

```

Congratulations, you have a running Muon service!
