

== A Microservice based system in 5 minutes

The quickest way to start a new Muon Java Microservice is to clone the example
repo at https://github.com/muoncore/muon-java-gradle-example

This is set up to use Gradle as the build tool and Java as the application
language.

First, install the Muon CLI, then clone this repository.

This project has an example service already in there that looks similar to

```java
include::src/main/java/io/muoncore/example/MuonServerExample.java[tags=main]
```
<1> Create a muon configuration using a fluent interface builder.
<1> Configure the AMQP transport to connect to the correct broker (see transport, below)
<1> Configure the AMQP discovery to connect to the correct broker (see discovery, below)
<1> Create a Muon instance on the AMQP transport/ discovery
<1> Add an RPC Server to this Muon instance                       (see protocols, below)
<1> Add an RPC endpoint to the server
<1> When invoked, respond to the RPC request with some manufactured data.

You can run this from a prebuilt Gradle task

```bash
> ./gradlew runServer
```

You can then use the Muon CLI to interact with the new service, using the name `example-service` set above as it's identifier

```bash
> muon rpc example-service /
```

This accesses the `rpc` protocol and interacts with the `/` endpoint

You will see the results from the example service that should look like

```bash
david@patmos:~/$ muon rpc rpc://example-service/hello

┌────────────┬──────────────────────────────┬───────────────────────────────────────────────┐
│ STATUS     │ CONTENT/TYPE                 │ BODY                                          │
├────────────┼──────────────────────────────┼───────────────────────────────────────────────┤
│ 200        │ application/json             │ {"Hello":"world 1481639846708"}               │
└────────────┴──────────────────────────────┴───────────────────────────────────────────────┘

========= RESPONSE FULL BODY: ========================================================

{ Hello: 'world 1481639846708' }

```

Congratulations, you have a running Muon service!
