
Muon Java is the implementation of the Muon microservices toolkit, for the Java platform. Muon enables you to easily build
microservices in many languages that have richer, more performant and fully reactive communication semantics and gain access
to Muon compatible services written in other languages without having to sacrifice the rich semantics or performance.

== A Microservice based system in 5 minutes

The quickest way to start a new Muon Java Microservice is to use _Spring Boot_ and the _Spring CLI_. You can see deeper information
later in this guide.

You can install this by following the instructions at spring.io or using _SDK Man_

[source,bash]
```
curl -s get.sdkman.io | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"

sdk install springboot
```

You can then create a new Spring Boot based application as a Groovy script.

[source,groovy,indent=0]
----
include::/src/main/groovy/io/muoncore/example/user/UserService.groovy[lines=17..32]
----
<1> Use Spring Boot annotations to start up a Muon instance.
<2> Declare that this class has Muon operations to discover
<3> Declare an RPC endpoint (see RPC).
<4> Send data back to the client, in this case including the current process identifier.

Here, we have configured a full muon service that makes available a single endpoint using the RPC _protocol_.  This protocol gives
an easy way to make a request and wait until a single response is received. Next, you can create another microservice
that exposes this to the outside world.

[source,groovy,indent=0]
----
include::src/main/groovy/io/muoncore/example/gateway/Gateway.groovy[lines=18..36]
----
<1> Gain access to the _muon_ instance that has been created.
<2> Configure Spring MVC to listen on an HTTP endpoint
<3> Use the muon instance to make an RPC call

Here, we have used Spring MVC, configured again via Spring Boot. This gives an easy way to start up an HTTP container
and make it accessible. When you call http://localhost:8080/ you will receive an http response. The body of that response
will be created from the data supplied by the UserService Microservice.

You have successfully built a distributed system, congratulations!

These will run in production, as independent services and require no underlying platform or runtime.

== Core Features

=== Reactive RPC

Request/ Response is a well understood communication style where you make a single request and expect to receive a single resonse

Muon supports this style of communication, over it's naturally scalable reactive and event based channel communication.

==== Simple RPC

Here is the simplest possible Muon RPC endpoint. It accepts any data pushed to it, and responsds with a simple text message

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPC.java[]
----

The client for this looks like

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPC.java[]
----

The Response object contains meta data about the reponse, if it succeeded.


==== Making it Reactive

The handler does not need to response synchronously as in the above example. The response can be invoked from any context, and by any thread.

This will cause an event to flow back down the channel and complete the request/ response cycle.

An example of this in action is

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPCAsync.java[]
----
//TODO, callouts and description

This demonstrates adding the requests onto a queue and processing them asynchronously.

Be aware that the request will time out on both the client and server side, depending on your configuration.

==== Batch handling RPC

A common failure of RPC based systems is that they attempt to perform too much work in concurrently, and in logical isolation.
This then ends up causing thread thrashing, overwhelming of the thread pool or overload on some backing data store.

Taking the above mechanism to it's logical conclusion, it becomes trivial to batch up the processing of request.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveRPCBatch.java[]
----

This example will, every 5 seconds, drain the queue, generate a single answer and send it to all of them.

=== Reactive Streams

Muon is built to enable the creation of streams easily. Internally everything is treated as a _channel_, a naturally streaming
construction.

This is best accessed via the Reactive Streams API, a cross industry effort to standardise streaming communication with back pressure.

To publish a new stream, create a _Publisher_ and pass it into the publishStream method, giving it a name, and the semantics of the stream.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveStreams.java[]
----

Here, we use _Spring Reactor_ to demonstrate the creation of a Publisher, however any Reactive Streams compatible framework or library could
be used.

To access the data from another service, use the subscribe method, passing in the logical Muon discovery url.

[source,java,indent=0]
----
include::src/main/java/io/muoncore/example/ReactiveStreams.java[]
----

Again, this example uses Java and shows two separate services communicating using a reactive message stream, with back pressure support
managed by Reactor.

=== Event Sourcing

TODO, link core event sourcing docs.

Apart from the recommended event store, Photon, Muon Java provides an in memory, simplified event store that only implements
 the core ingest and stream functionality of a muon compatible event store. You can read more about it link:InMemEventStore.html[here]

This is most useful during building tests.

=== Event Based Testing

If you adopt the Event system (which requires an event store such as _Photon_), then you will design your system domains
as a set of _Events_, and your business processes as a set of causal relationships between them.

=== Wiretap

The transport subsystem of Muon injects a WiretapChannel into every connection that is made. This allows you to optionally
read the messages moving in and out of the transport and further interpret them. The messages themselves are immutable,
and so you recieve the message itself for processing.

Ordinarily, this is used to record the way a service communicates with the rest of the distributed application. This
is particularly useful when designing and building a new communication protocol.

Image a service with a single RPC endpoint that accepts an undefined object data structure, which represent using a Map.
 It then responds inline wth the number 42. A very simple service.

[source,java]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=setupRPC]
----

We would like to generate a list of all the services that are calling this one, without altering the business method.

We could implement this using a wiretap, this will extract a stream of all the requests that match a particular filter.
The stream interface provided implements the Reactive Stream interface.

[source,java]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=wiretap]
----
<1> The services that have connected to this one via the RPC endpont.
<2> A Spring Reactor Broadcaster, converting the messages into the list.
<3> Adding the tap into the Muon transport subsystem
<4> The filter matches for the EventType field on the TransportMessage, picking out particular messages.

Whenever you then perform an RPC communication, the Request ```TransportMessage``` events will be selected by your wiretap
 and passed into the Subscriber, in this case the Reactor Broadcaster.

[source,java]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=fireRPC]
----

As many wiretaps as you like can be active. You may add another Wiretap later on to select the Response messages, and it will then begin
to receive all the messages required.

[source,java]
----
include::src/main/java/io/muoncore/example/Wiretap.java[tags=wiretap2]
----

== Spring Support

Muon Java does not require Spring Core to run, however it does have a set of integrations for Spring and in particular, Spring Boot.

=== Create an new Muon Spring Boot Microservice

To create a new Muon Spring Boot Microservice, you need to

[source,java]
----
include::src/main/java/io/muoncore/example/springexample/AutowireMuon.java[tags=autowire]
----

=== Provide an RPC endpoint

=== Create a Spring Repository

=== Subscribe to a Remote Stream

=== Obtain the Muon object

Currently, not all features of Muon are fully exposed in the spring support.

You can obtain the current Muon instance that has been automatically created via a simple @Autowire and then perform
any of the actions you find in the rest of the documentation on it.

Here is an example of this, combined with a @PostConstruct to allow a wiretap to be set up.

[source,java]
----
include::src/main/java/io/muoncore/example/springexample/AutowireMuon.java[tags=autowire]
----

== Extending Muon Java

In common with all Muon libraries, Muon Java is a restricted implementation of Communicating Sequential Processes.
Extension then mostly involves creating and exposing various combinations of processes and channels.

=== Encoding



=== Transports



=== Adding a new interaction protocol

Before reading on, many systems won't need to do this. The baked in protocols (RPC, Streaming etc) are generally good enough
in most circumstances. If you do have a specific need to control the way your services interact in a more granular way then read on!

To implement a new protocol, you need to define the API(s) that you want to provide to your users, define the event interchange
that will need to happen to communicate that between services, and then create the processes need to bring those events to life.

This guide focuses on how to implement this in Muon-Java. For a fuller discussion on event protocols, see the main guide.

TODO, link to main guide on protocols

==== Designing a Protocol

==== Client Side

===== Designing Building a Muon Client Process

===== Designing the User API and Protocol Stack

==== Server Side

===== Designing Building a Muon Server Process

===== Registering the ServerStack
